export const de = {
	titleOnboarding1: 'Extrem hochwertige Hintergrundbilder',
	descriptionOnboarding1: 'Verschiedene 4k-Auflösung Hintergrundbilder zur Auswahl',
	titleOnboarding2: 'Täglich neue Hintergrundbilder',
	descriptionOnboarding2: 'Brandneue 4k-Hintergrundbilder werden täglich hinzugefügt',
	titleOnboarding3: 'Für Startbildschirm und Sperrbildschirm einstellen',
	descriptionOnboarding3:
		'Einfach dein Lieblingshintergrundbild sowohl für den Startbildschirm als auch für den Sperrbildschirm einstellen',
	next: 'Weiter',
	started: 'Loslegen',
	language: 'Sprache',
	popular: 'Beliebt',
	category: 'Kategorie',
	favorites: 'Favoriten',
	moreApp: 'Weitere Apps',
	tof: 'Nutzungsbedingungen',
	policy: 'Datenschutz',
	more: 'Mehr',
	homeScreen: 'Startbildschirm',
	lockscreen: 'Sperrbildschirm',
	apply: 'Anwenden',
	questionWallpaper: 'Möchtest du dieses Hintergrundbild für welchen Bildschirm verwenden?',
	option1: 'Beide: Startbildschirm und Sperrbildschirm',
	option2: 'Als Startbildschirm festlegen',
	option3: 'Als Sperrbildschirm festlegen',
	cancel: 'Abbrechen',
	success: 'Erfolgreich',
	wallpaper: 'Hintergrundbilder',
	menu: 'Speisekarte',
};
