export const en = {
	titleOnboarding1: 'Extremely high quality wallpapers',
	descriptionOnboarding1: 'Various 4k resolution wallpapers for you to choose',
	titleOnboarding2: 'Daily new wallpapers',
	descriptionOnboarding2: 'Brand new 4k wallpapers come round daily',
	titleOnboarding3: 'Set for homescreen and lockscreen',
	descriptionOnboarding3: 'Easy to set your favourite wallpaper as both homescreen and lockscreen',
	next: 'Next',
	started: 'Get Started',
	language: 'Language',
	popular: 'Popular',
	category: 'Category',
	favorites: 'Favorites',
	moreApp: 'More apps',
	tof: 'Terms and Conditions',
	policy: 'Policy',
	more: 'More',
	homeScreen: 'Homescreen',
	lockscreen: 'Lockscreen',
	apply: 'Apply',
	questionWallpaper: 'Do you want to use this wallpaper for which screen?',
	option1: 'Both Homescreen & Lockscreen',
	option2: 'Set as Homescreen',
	option3: 'Set as Lockscreen',
	cancel: 'Cancel',
	success: 'Success',
	wallpaper: 'Wallpapers',
};
