export const es = {
	titleOnboarding1: 'Fondos de pantalla de alta calidad',
	descriptionOnboarding1: 'Diversos fondos de pantalla en resolución 4k para que elijas',
	titleOnboarding2: 'Nuevos fondos de pantalla diarios',
	descriptionOnboarding2: 'Nuevos fondos de pantalla en resolución 4k todos los días',
	titleOnboarding3: 'Establecer para pantalla de inicio y bloqueo',
	descriptionOnboarding3:
		'Fácil de establecer tu fondo de pantalla favorito tanto en la pantalla de inicio como en la de bloqueo',
	next: 'Siguiente',
	started: 'Empezar',
	language: 'Idioma',
	popular: 'Popular',
	category: 'Categoría',
	favorites: 'Favoritos',
	moreApp: 'Más aplicaciones',
	tof: 'Términos y Condiciones',
	policy: 'Política',
	more: 'Más',
	homeScreen: 'Pantalla de inicio',
	lockscreen: 'Pantalla de bloqueo',
	apply: 'Aplicar',
	questionWallpaper: '¿Deseas usar este fondo de pantalla para qué pantalla?',
	option1: 'Ambas: Pantalla de inicio y bloqueo',
	option2: 'Establecer como Pantalla de inicio',
	option3: 'Establecer como Pantalla de bloqueo',
	cancel: 'Cancelar',
	success: 'Éxito',
	wallpaper: 'Fondos de pantalla',
};
