export const fr = {
	titleOnboarding1: "Fonds d'écran de qualité extrêmement élevée",
	descriptionOnboarding1: "Divers fonds d'écran en résolution 4k à choisir",
	titleOnboarding2: "Nouveaux fonds d'écran quotidiens",
	descriptionOnboarding2: "De nouveaux fonds d'écran 4k sont disponibles tous les jours",
	titleOnboarding3: "Définir pour l'écran d'accueil et l'écran de verrouillage",
	descriptionOnboarding3:
		"Facile à définir votre fond d'écran préféré à la fois pour l'écran d'accueil et l'écran de verrouillage",
	next: 'Suivant',
	started: 'Commencer',
	language: 'Langue',
	popular: 'Populaire',
	category: 'Catégorie',
	favorites: 'Favoris',
	moreApp: "Plus d'applications",
	tof: 'Termes et Conditions',
	policy: 'Politique',
	more: 'Plus',
	homeScreen: "Écran d'accueil",
	lockscreen: 'Écran de verrouillage',
	apply: 'Appliquer',
	questionWallpaper: "Voulez-vous utiliser ce fond d'écran pour quel écran?",
	option1: "Écran d'accueil et écran de verrouillage",
	option2: "Définir comme écran d'accueil",
	option3: 'Définir comme écran de verrouillage',
	cancel: 'Annuler',
	success: 'Succès',
};
