export const hi = {
	titleOnboarding1: 'बहुत उच्च गुणवत्ता वालपेपर',
	descriptionOnboarding1: 'आपके लिए विभिन्न 4k रेज़ोल्यूशन वालपेपर चुनने के लिए',
	titleOnboarding2: 'रोज़ाना नए वालपेपर',
	descriptionOnboarding2: 'ब्रांड नए 4k रेज़ोल्यूशन वालपेपर दैनिक रूप से आते हैं',
	titleOnboarding3: 'होमस्क्रीन और लॉकस्क्रीन के लिए सेट करें',
	descriptionOnboarding3:
		'अपने पसंदीदा वालपेपर को होमस्क्रीन और लॉकस्क्रीन दोनों के रूप में सेट करना आसान',
	next: 'अगला',
	started: 'शुरू करें',
	language: 'भाषा',
	popular: 'लोकप्रिय',
	category: 'श्रेणी',
	favorites: 'पसंदीदा',
	moreApp: 'और एप्लिकेशन',
	tof: 'नियम और शर्तें',
	policy: 'नीति',
	more: 'अधिक',
	homeScreen: 'होमस्क्रीन',
	lockscreen: 'लॉकस्क्रीन',
	apply: 'लागू करें',
	questionWallpaper: 'क्या आप इस वालपेपर का उपयोग किस स्क्रीन के लिए करना चाहते हैं?',
	option1: 'दोनों होमस्क्रीन और लॉकस्क्रीन',
	option2: 'होमस्क्रीन के रूप में सेट करें',
	option3: 'लॉकस्क्रीन के रूप में सेट करें',
	cancel: 'रद्द करें',
	success: 'सफलता',
	wallpaper: 'वॉलपेपर',
};
