export const pt = {
	titleOnboarding1: 'Papéis de parede de alta qualidade',
	descriptionOnboarding1: 'Vários papéis de parede em resolução 4k para você escolher',
	titleOnboarding2: 'Novos papéis de parede diários',
	descriptionOnboarding2: 'Novos papéis de parede em resolução 4k todos os dias',
	titleOnboarding3: 'Definir para tela inicial e tela de bloqueio',
	descriptionOnboarding3:
		'Fácil de definir seu papel de parede favorito tanto na tela inicial quanto na tela de bloqueio',
	next: 'Próximo',
	started: 'Começar',
	language: 'Linguagem',
	popular: 'Popular',
	category: 'Categoria',
	favorites: 'Favoritos',
	moreApp: 'Mais aplicativos',
	tof: 'Termos e Condições',
	policy: 'Política',
	more: 'Mais',
	homeScreen: 'Tela inicial',
	lockscreen: 'Tela de bloqueio',
	apply: 'Aplicar',
	questionWallpaper: 'Você deseja usar este papel de parede para qual tela?',
	option1: 'Ambas: Tela inicial e tela de bloqueio',
	option2: 'Definir como Tela inicial',
	option3: 'Definir como Tela de bloqueio',
	cancel: 'Cancelar',
	success: 'Sucesso',
	wallpaper: 'Papéis de parede',
	menu: 'Menu',
};
