export const images = {
	ic_back: require('./images/ic_back.png'),
	ic_search: require('./images/ic_search.png'),
	ic_menu_left: require('./images/ic_menu_left.png'),
	image_category: require('./images/image_category.png'),
	ic_back_arrow: require('./images/ic_back_arrow.png'),
	banner: require('./images/banner.png'),
	banner_default: require('./images/banner_default.png'),
	ic_like: require('./images/ic_like.png'),
	ic_liked: require('./images/ic_liked.png'),
	ic_home: require('./images/ic_home.png'),
	ic_home_selected: require('./images/ic_home_selected.png'),
	ic_lock: require('./images/ic_lock.png'),
	ic_lock_selected: require('./images/ic_lock_selected.png'),
	onboarding: require('./images/onboarding.png'),
	ic_success: require('./images/ic_success.png'),
	ic_checkbox: require('./images/ic_checkbox.png'),
	ic_checkbox_checked: require('./images/ic_checkbox_checked.png'),
	ic_premium: require('./images/ic_premium.png'),
	ic_rate: require('./images/ic_rate.png'),
	ic_language: require('./images/ic_language.png'),
	ic_term: require('./images/ic_term.png'),
	ic_more_app: require('./images/ic_more_app.png'),
};
